version: "3.7"

x-app-common: &app-common
  volumes:
    - .:/app
  build:
    context: .
    dockerfile: Dockerfile
  env_file: .env
  tty: true
  privileged: true
  depends_on:
    - db
  restart: unless-stopped
  stdin_open: true

services:
  api:
    <<: *app-common
#    entrypoint: /app/entrypoint.sh
  cli:
    <<: *app-common
    command: echo "Starting cli container..."
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: